// <auto-generated />
namespace NepaliRasoi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addednewpropertiestouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewpropertiestouser));
        
        string IMigrationMetadata.Id
        {
            get { return "202004190006280_addednewpropertiestouser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
